import Head from "next/head";
import Image from "next/image";
import image from "../public/images/image444.png";
import Box from "@mui/material/Box";
import Title from "../components/heroComp/title.js";
import styles from "../styles/Hero.module.css";
import { Container } from "@mui/system";
import Body from "../components/heroComp/body.js";
import Counter from "../components/counterComp/counter";

export default function Hero() {
  return (
    <>
      <Head>
        <title>ReFood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image1.png" size />
      </Head>

      <Box className={styles.BoxContainer}>
        <Box className={styles.titleBodyBox}>
          <Title />
          <Body />
          <Box sx={{marginTop:'10vh'}}>
            <Counter />
          </Box>
        </Box>
        <Box className={styles.imageContainer}>
          <Image height={350} width={450} src={image} />
        </Box>
      </Box>

      {/* <Image   width={300} src ={image3} /> */}
    </>
  );
}
