import { Container } from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head";
import FactoryTwoToneIcon from "@mui/icons-material/FactoryRounded";
import FoodBankTwoToneIcon from "@mui/icons-material/FoodBankRounded";
import BoxButton from "../components/boxButtonComp/boxButton";
import styles from "../styles/startNow.module.css";
const StartNow = () => {
  return (
    <>
      <Head>
        <title>Food Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Box className={styles.boxContainer}>
          <BoxButton
            title="Create Reciving Account"
            orient="left"
            icon={<FactoryTwoToneIcon sx={{ mt: 4, fontSize: 80 }} />}
          >
            This type of Account is for Organizations like Food Charities and
            Food Recyling Factories, that want to use the ReFood to view and
            recive Food Giveaways.
          </BoxButton>

          <BoxButton
            title="Create Giving Account"
            orient="right"
            icon={<FoodBankTwoToneIcon sx={{ mt: 4, fontSize: 80 }} />}
          >
            This type of Account is for any Person or Organizations like Restaurants, Hotels,
            Malls, that have leftover food and want to use ReFood to giveaway food.
          </BoxButton>
        </Box>
      </Container>
    </>
  );
};
export default StartNow;
