import * as  React from "react";
import Head from "next/head";
import FactoryTwoToneIcon from "@mui/icons-material/FactoryRounded";
import FoodBankTwoToneIcon from "@mui/icons-material/FoodBankRounded";
import BoxButton from "../components/boxButtonComp/boxButton";
import styles from "../styles/startNow.module.css";
import Avatar from '@mui/material/Avatar';
import Button from '@mui/material/Button';
import CssBaseline from '@mui/material/CssBaseline';
import TextField from '@mui/material/TextField';
import FormControlLabel from '@mui/material/FormControlLabel';
import Checkbox from '@mui/material/Checkbox';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import LockOutlinedIcon from '@mui/icons-material/LockOutlined';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import { useSignup } from "../hooks/useSignup"
import image1 from "../public/images/image77.jpg";
import Paper from "@mui/material/Paper";
import Link from 'next/link';
import { useRouter } from 'next/router'


function Copyright(props) {

  return (
    <Typography variant="body2" color="text.secondary" align="center" {...props}>
      {'Copyright © '}
      <Link href="/" >
        Refood
      </Link>{' '}
      {new Date().getFullYear()}
      {'.'}
    </Typography>
  );
}

// TODO remove, this demo shouldn't need to reset the theme.


export default function SignUp() {
  const [userType,setUserType] = React.useState(null);
  const {signup, error, isLoading} = useSignup()
  const router = useRouter()

  const handleSubmit = async (event) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    console.log({
      email: data.get('email'),
      password: data.get('password'),
    });
    await signup(data.get('email'),data.get('password'),userType)
    router.push('/signIn')

  }
  
  
  return ( 
    <>
    <Head>
    <title>Food Management System</title>
    <meta name="description" content="Generated by create next app" />
   <meta name="viewport" content="width=device-width, initial-scale=1" />
   <link rel="icon" href="/favicon.ico" />
    </Head>

    {(userType =="Donator" ||userType == "Factory"||userType == "Charity") &&
      <Grid container component="main" sx={{ mt: "9vh", height: "96vh" }}>
      <CssBaseline />

      <Grid
        item
        xs={12}
        sm={12}
        md={5}
        component={Paper}
        elevation={0}
        square
      >
       <Box
        sx={{
          pt: 3,
          px: 4,
          // marginTop: 8,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        <Avatar sx={{ m: 1, bgcolor: 'primary.main' }}>
          <LockOutlinedIcon />
        </Avatar>
        <Typography component="h1" variant="h5">
          Sign up
        </Typography>
        <Box component="form" noValidate onSubmit={handleSubmit} sx={{ mt: 3,width:"70%",}}>
          <Grid container spacing={2}>
            <Grid item xs={12} >
              <TextField
                autoComplete="given-name"
                name="firstName"
                required
                fullWidth
                id="firstName"
                label="OrganiztionName/FullName"
                autoFocus
              />
            </Grid>
           
            <Grid item xs={12}>
              <TextField
                required
                fullWidth
                id="email"
                label="Email Address"
                name="email"
                autoComplete="email"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                required
                fullWidth
                name="password"
                label="Password"
                type="password"
                id="password"
                autoComplete="new-password"
              />
            </Grid>
            <Grid item xs={12}>
              {/* <FormControlLabel
                control={<Checkbox value="allowExtraEmails" color="primary" />}
                label="I want to receive inspiration, marketing promotions and updates via email."
              /> */}
            </Grid>
          </Grid>
          <Button
            type="submit"
            fullWidth
            variant="contained"
            sx={{ mt: 3, mb: 2 }}
          >
            Sign Up
          </Button>
          <Grid container justifyContent="flex-end">
            <Grid item>
              <Link href="/signIn" >
                <Typography variant="body2" >
                Already have an account? Sign in
                </Typography>
              </Link>
            </Grid>
          </Grid>
          </Box>
        </Box>
       <Copyright sx={{ mt: 5 }} />
          
        
      </Grid>
      <Grid item xs={0} sm={0} md={7}>
        <Box
          sx={{
            height: "100%",

            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <img style={{ width: "75%", height: "75%" }} src={image1.src} />
          {/* <Image width={800} src={image1} /> */}
        </Box>
      </Grid>
    </Grid>
}
  
    
        {!userType && 
          <Container>
            <Box className={styles.boxContainer}>
             <BoxButton
                title="Create Reciving Account"
                orient="left"
                icon={<FactoryTwoToneIcon sx={{ mt: 4, fontSize: 80 }} />}
                onClick={()=>setUserType("Reciving")}
              >
                This type of Account is for Organizations like Food Charities and
                Food Recyling Factories, that want to use the ReFood to view and
                recive Food Giveaways.
              </BoxButton>
    
              <BoxButton
                onClick={()=>setUserType("Donator")}
                title="Create Giving Account"
                orient="right"
                icon={<FoodBankTwoToneIcon sx={{ mt: 4, fontSize: 80 }} />}
              >
                This type of Account is for any Person or Organizations like Restaurants, Hotels,
                Malls, that have leftover food and want to use ReFood to giveaway food.
              </BoxButton>
            </Box>
            
          </Container>}

          { userType == "Reciving" &&
          <Container>
            <Box className={styles.boxContainer}>
             <BoxButton
                title="Food Charity"
                orient="left"
                icon={<FoodBankTwoToneIcon sx={{ mt: 4, fontSize: 80 }} />}
              
                onClick={()=>setUserType("Charity")}
              >
                for food charities
              </BoxButton>
    
              <BoxButton
                onClick={()=>setUserType("Factory")}
                title="Food Recyling Factory"
                orient="right"
                icon={<FactoryTwoToneIcon sx={{ mt: 4, fontSize: 80 }} />}
               
              >
                for food factories
              </BoxButton>
            </Box>
            
          </Container>




          }


        </>
  );}

// const StartNow = () => {
// const [buttonClicked,setButtonClicked] = React.useState(false);
//   return (
//     <>
//       <Head>
//         <title>Food Management System</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <Container>
//         <Box className={styles.boxContainer}>
//           <BoxButton
//             title="Create Reciving Account"
//             orient="left"
//             icon={<FactoryTwoToneIcon sx={{ mt: 4, fontSize: 80 }} />}
//           >
//             This type of Account is for Organizations like Food Charities and
//             Food Recyling Factories, that want to use the ReFood to view and
//             recive Food Giveaways.
//           </BoxButton>

//           <BoxButton
//             title="Create Giving Account"
//             orient="right"
//             icon={<FoodBankTwoToneIcon sx={{ mt: 4, fontSize: 80 }} />}
//           >
//             This type of Account is for any Person or Organizations like Restaurants, Hotels,
//             Malls, that have leftover food and want to use ReFood to giveaway food.
//           </BoxButton>
//         </Box>
        
//       </Container>
//     </>
//   );
// };
// export default StartNow;
