import Head from "next/head";
import Map from "../components/mapComp/map";
import {
  DataGrid,
  GridRowsProp,
  GridColDef,
  GridToolbar,
} from "@mui/x-data-grid";
import { useDemoData } from "@mui/x-data-grid-generator";
import Grid from "@mui/material/Grid";
import Paper from "@mui/material/Paper";
import ButtonGroup from "@mui/material/ButtonGroup";
import Button from "@mui/material/Button";

const Buttons = () => {
  return(
  <ButtonGroup
    disableElevation
    variant="text"
    aria-label="Disabled elevation buttons"
    orientation="vertical"
    size="small"
  >
    <Button>Accept</Button>
    <Button color={"error"}>Reject</Button>
  </ButtonGroup>);
};
const columns = [
  { field: "col1", headerName: "Time", width: 80},
  { field: "col2", headerName: "Location", width: 270 },
  { field: "col3", headerName: "Quantity", width: 70 },
  { field: "col4", headerName: "Unit", width: 52 },
  { field: "col5", headerName: "Due", width: 80 },
  { field: "col6", headerName: "Actions", width: 80 ,renderCell: ()=>((<Buttons/>))},
  { field: "col7", headerName: "Remarks", width: 170 },
];

const rows = [
  {
    id: 1,
    col1: "17-02-23 21:51",
    col2: "150, Abu Mehjan Al Thaqafi, Tanzeem Kafarsouseh, Damascus, Syria",
    col3: "150",
    col4: "meal",
    col5: "18-2-23 21:00",
    col7:"No Remarks"
  },
  {
    id: 2,
    col1: "17-2-23 21:51",
    col2: "150, Abu Mehjan Al Thaqafi, Tanzeem Kafarsouseh, Damascus, Syria",
    col3: "150",
    col4: "meal",
    col5: "18-2-23 21:00",
    
    col7:"No Remarks"
  },

  {
    id: 3,
    col1: "17-2-23 21:51",
    col2: "150, Abu Mehjan Al Thaqafi, Tanzeem Kafarsouseh, Damascus, Syria",
    col3: "150",
    col4: "meal",
    col5: "18-2-23 21:00",
    col7:"No Remarks"
  },
  {
    id: 4,
    col1: "17-2-23 21:51",
    col2: "150, Abu Mehjan Al Thaqafi, Tanzeem Kafarsouseh, Damascus, Syria",
    col3: "150",
    col4: "meal",
    col5: "18-2-23 21:00",
    col7:"No Remarks"
  },
  {
    id: 5,
    col1: "17-2-23 21:51",
    col2: "150, Abu Mehjan Al Thaqafi, Tanzeem Kafarsouseh, Damascus, Syria",
    col3: "150",
    col4: "meal",
    col5: "18-2-23 21:00",
    col7:"No Remarks"
  },






];  

const TakerPage = () => {
  return (
    <>
      <Head>
        <title>ReFood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image1.png" size />
      </Head>

      <Grid container
        spacing={3} sx={{marginTop:'8.5vh',height:'90vh',paddingX:'1.3em',paddingY:'0'}}
      >
        <Grid item xs={12} md={8} >
          <DataGrid
            rows={rows}
            columns={columns}
            components={{
              Toolbar: GridToolbar,
            }}
            getRowHeight={() => 'auto'}
          />
        </Grid>
        <Grid item xs={12} md={4}  sx={{marginTop:'10px'}}>
          <Map />
        </Grid>
      </Grid>
      
    </>
  );
};
export default TakerPage;
